// const editorTheme = {
//     ltr: "ltr",
//     rtl: "rtl",
//     placeholder: "editor-placeholder",
//     paragraph: "mb-2 relative",
//     quote: "pl-4 border-l-4 border-gray-300 dark:border-gray-700 my-4 text-gray-700 dark:text-gray-300",
//     heading: {
//       h1: "text-3xl font-extrabold dark:text-white",
//       h2: "text-xl font-bold dark:text-white",
//       h3: "text-lg font-bold dark:text-white",
//       h4: "text-base font-bold dark:text-white",
//       h5: "text-sm font-bold dark:text-white",
//       h6: "text-xs font-bold dark:text-white",
//     },
//     list: {
//       nested: {
//         listitem: "pl-4 mt-1",
//       },
//       ol: "list-decimal pl-4 my-2 space-y-1",
//       ul: "list-disc pl-4 my-2 space-y-1",
//       listitem: "my-0.5 text-gray-800 dark:text-gray-200",
//       olDepth: [
//         "list-decimal",
//         "list-[lower-alpha]",
//         "list-[lower-roman]",
//         "list-[decimal]",
//         "list-[upper-alpha]",
//       ],
//     },
//     image: "editor-image",
//     link: "font-medium text-blue-600 dark:text-blue-500 hover:underline",
//     text: {
//       bold: "font-bold",
//       italic: "italic",
//       overflowed: "editor-text-overflowed",
//       hashtag: "editor-text-hashtag",
//       underline: "underline",
//       strikethrough: "line-through",
//       underlineStrikethrough: "underline line-through",
//       code: "font-mono text-[94%] bg-gray-100 dark:bg-gray-600 dark:text-white p-1 rounded",
//     },
//     code: "bg-gray-100 dark:bg-gray-800 rounded px-1.5 py-0.5 font-mono text-sm",
//     codeBlock: "bg-gray-100 dark:bg-gray-800 rounded-lg p-4 font-mono text-sm my-4",
//     codeHighlight: {
//       atrule: "text-[#07a] dark:text-cyan-400",
//       attr: "text-[#07a] dark:text-cyan-400",
//       boolean: "text-pink-700 dark:text-pink-400",
//       builtin: "text-[#690]",
//       cdata: "bg-slate-600",
//       char: "text-[#690]",
//       class: "text-[#dd4a68]",
//       "class-name": "text-[#dd4a68]",
//       comment: "bg-slate-600 dark:bg-gray-600",
//       constant: "text-pink-700 dark:text-pink-400",
//       deleted: "text-pink-700 dark:text-pink-400",
//       doctype: "bg-slate-600",
//       entity: "text-[#9a6e3a]",
//       function: "text-[#dd4a68]",
//       important: "text-[#e90]",
//       inserted: "text-[#690]",
//       keyword: "text-[#07a] dark:text-cyan-400",
//       namespace: "text-[#e90] dark:text-blue-400",
//       number: "text-pink-700 dark:text-pink-400",
//       operator: "text-[#9a6e3a]",
//       prolog: "bg-slate-600",
//       property: "text-pink-700 dark:text-pink-400",
//       punctuation: "text-[#999]",
//       regex: "text-[#e90] dark:text-blue-400",
//       selector: "text-[#690]",
//       string: "text-[#690] dark:text-orange-500",
//       symbol: "text-pink-700 dark:text-pink-400",
//       tag: "text-pink-700 dark:text-pink-400",
//       url: "text-[#9a6e3a]",
//       variable: "text-[#e90] dark:text-blue-400",
//     },
//   };
  
//   export default editorTheme;